# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-22 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni_data',
            name='rcode',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='alumni_profile',
            name='company',
            field=models.CharField(default='<Work Not Available>', max_length=50),
        ),
        migrations.AlterField(
            model_name='alumni_profile',
            name='contact',
            field=models.CharField(default='<Contact Not Available>', max_length=25),
        ),
        migrations.AlterField(
            model_name='alumni_profile',
            name='location',
            field=models.CharField(default='<Location Not Available>', max_length=50),
        ),
        migrations.AlterField(
            model_name='alumni_profile',
            name='yog',
            field=models.CharField(max_length=10),
        ),
    ]
