# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-24 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rl', '0005_auto_20180623_2157'),
    ]

    operations = [
        migrations.CreateModel(
            name='adder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=75)),
                ('sname', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=75)),
                ('pswd', models.CharField(max_length=75)),
            ],
        ),
    ]
