# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-25 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rl', '0007_loc_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alumni_data',
        ),
        migrations.DeleteModel(
            name='alumni_profile',
        ),
        migrations.DeleteModel(
            name='feedbackmodel',
        ),
    ]
